Added Manish's info
adviksinghania/expert-octo-cat pull request #9
Opened 2022-10-02 19:41 UTC by Manice18

2022-10-03 04:33 UTC, adviksinghania requested changes

2022-10-03 04:33 UTC, adviksinghania commented on Manice.md
> +# Manish Saha
The heading is supposed to have 3 hashes, making it an H3 heading and not the main H1.

2022-10-03 07:40 UTC, Manice18 commented
Done @adviksinghania

2022-10-03 18:36 UTC, Manice18 commented
Please merge this one @adviksinghania . And please comment if there are any more mistakes.

2022-10-04 04:06 UTC, adviksinghania approved these changes
Nice

2022-10-04 04:07 UTC, merged